version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: project_lab_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: project_lab
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: project_lab_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: localhost
      DB_PASSWORD: bruno123
      DB_NAME: project_lab

  frontend:
    build: ./frontend
    container_name: project_lab_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
